name: Deploy Backend to Heroku

on:
  push:
    branches:
      - develop
    paths:
      - 'backend/**'
  workflow_dispatch: # This enables manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install Dependencies
      run: |
        ls -a
        cd backend
        npm i

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: "backend"
      env:
        HD_NODE_ENV: "production"
        HD_PORT: ${{ secrets.PORT }}
        HD_DB_PATH: ${{ secrets.DB_PATH }}
